# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b974cef4-a047-4aff-b5e9-fbc43e6249ce'
  imageRepository: 'juancsotopipelinesjavascriptdocker'
  containerRegistry: 'containerregistrypruebas.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Suscripción de Visual Studio Enterprise(1)(ce5edc26-505c-4440-ad07-15c0e09e4f95)'
        KeyVaultName: 'GruVarProyectosPruebas'
        SecretsFilter: 'EditableOptions'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Inicia container
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
    - script : |
         docker run -e AZP_URL=https://dev.azure.com/Jsotoc/ -e AZP_TOKEN=$(kvpat) -e AZP_AGENT_NAME=SelfHostedAgentContainers -e AZP_POOL=SelfHostedPool containerregistrypruebas.azurecr.io/dockeragent:v1