apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-b5e2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-b5e2"
  template:
    metadata:
      labels:
        app: "myakscluster-b5e2"
    spec:
      containers:
        - name: "myakscluster-b5e2"
          image: "containerregistrypruebas.azurecr.io/myakscluster"
          ports:
          - containerPort: 80