on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerregistrypruebas.azurecr.io
        username: ${{ secrets.acr_containerregistrypruebas_username }}
        password: ${{ secrets.acr_containerregistrypruebas_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "app/Dockerfile" -t containerregistrypruebas.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=app/Dockerfile
        docker push containerregistrypruebas.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksclusterb2b1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksclusterb2b1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksclusterb2b1
        container-registry-url: containerregistrypruebas.azurecr.io
        container-registry-username: ${{ secrets.acr_containerregistrypruebas_username }}
        container-registry-password: ${{ secrets.acr_containerregistrypruebas_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksclusterb2b1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          containerregistrypruebas.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
